# Where the homeserver's Client-Server API is located. Typically this
# is where clients would be connecting to in order to send messages.
homeserverUrl: "https://matrix-client.matrix.org"

# An access token for the bot to use. Learn how to get an access token
# at https://t2bot.io/docs/access_tokens
accessToken: "YOUR_TOKEN_HERE"

# Location on disk for where to store various bot information.
dataPath: "storage"

# The ID of the room to use as a management room. The bot will only
# accept commands in here.
managementRoom: "!room:example.org"

# This secret is used to encrypt various details of information in the bot's
# internal storage, such as MXIDs and Email Addresses. This information should
# only ever be accessible to the bot, but extra measures are taken for these
# sorts of identifiers.
#
# MUST BE 32 CHARACTERS EXACTLY. DO NOT CHANGE AFTER SETTING.
secretKey: "SET_TO_RANDOM_VALUE"  # You should change this.

# The identity server to use to send email invites to any participants. The
# bot will accept all terms of service automatically - please ensure that it
# has legal capability to do so before running the bot in this way.
idServerDomain: "vector.im"

# Configuration for the webserver (used to serve widgets for the conference's
# rooms).
webserver:
  # The address to bind to. If using Docker, this should be all interfaces and
  # instead managed through port mapping.
  address: '0.0.0.0'

  # The port to bind the webserver on.
  port: 8080

  # The public URL where the bot can expect to be able to serve widgets from.
  # Note that this URL will be put into the Matrix room state.
  publicBaseUrl: "https://conferences.example.org"

  # Additional assets may be served from `${publicBaseUrl}/assets/*` which are
  # available at this path.
  additionalAssetsPath: "/data/public"

# Information about the conference
conference:
  # The ID of the conference to call this one. Data from other conferences
  # will be ignored (such as past conferences). This will also be used to create
  # the Matrix Space.
  id: "fosdem2021"

  # The name of the conference.
  name: "FOSDEM 2021"

  # The URL to the XML which is updated with conference information.
  # This is read and parsed by the bot during the early stages of
  # setting up the conference.
  pentabarfDefinition: "https://fosdem.org/2021/schedule/xml"

  # The timezone that the pentabarf definition is in.
  timezone: "Europe/Brussels"

  # Various prefixes used by the bot when parsing information.
  prefixes:
    # The prefixes for the rooms listed in the pentabarf definition which
    # describe the rooms that are 'auditorium' rooms. The prefixes will be
    # trimmed when naming the room.
    auditoriumRooms: ["D."]

    # The prefixes for the rooms listed in the pentabarf definition which
    # describe the rooms that are 'special interest' rooms. The prefixes will
    # be trimmed when naming the room.
    interestRooms: ["S.", "B."]

    # The prefix to apply to all generated room aliases.
    aliases: ""
